### PR TITLE
Adding pip installation

### LINKED ISSUE #147: Fix build script

### PR DESCRIPTION
**Pull request by saikirankv**
fixes #147

### CODE REVIEW

**Comment by JaDogg** [comment]
@saikirankv check the build result: https://github.com/JaDogg/pydoro/runs/1192257942?check_suite_focus=true
it still seem to fail. Something to do with Permission on windows box

**Comment by saikirankv** [comment]
Yes, its failed with permission denied error. As we are not using a custom image the permission error shouldn't be raised. I'll check.

**Comment by saikirankv** [comment]
@JaDogg build issue is fixed, now it takes around 1m 27s to run the checks.
I suggest a few enhancements here, in your windowns_latest image create a .venv prior and install all the requirements there. 
When we run the pr checks we can run pip install command once again only the new req. will be installed with this build time will be reduced.

1m 27s is ok, but you can consider my suggestion in the future where if you have a bunch of packages and checks to be performed.

**Comment by JaDogg** [comment]
@saikirankv Thank you :) Merged

**Pull request merged**
